import api from './api/client.js';
export * from './api/authApi.js';
export * from './api/userApi.js';
export * from './api/taskApi.js';
export * from './api/notificationApi.js';
export * from './api/departmentApi.js';
export * from './api/branchApi.js';
export * from './api/emailLogApi.js';
export default api;
export const hardDeleteDocument = (type, id) => api.delete(`/trash/${type}/${id}`);
